version: '3'
services:
  mysql_db:
    container_name: mysql_db
    hostname: mysql_db
    image: mysql:8.1.0
    ports:
      - "32001:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: unless-stopped
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  wsgi_app:
    container_name: wsgi_app
    hostname: wsgi_app
    build: 
      context: .
      dockerfile: Dockerfile.service
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - mysql_db