version: '3'
services:
  phpmyadmin:
  container_name: phpmyadmin
  hostname: phpmyadmin
  image: phpmyadmin:5.2.1
  restart: always
  links:
    - mysql_db
  ports:
    - 8080:80
  environment:
    - PMA_HOST=mysql_db
    - MYSQL_USERNAME=root
    - MYSQL_ROOT_PASSWORD=secret
    - PMA_PORT=3306
    - PMA_ARBITRARY=1
  mysql_db:
    container_name: mysql_db
    hostname: mysql_db
    image: mysql:8.1.0
    ports:
      - "32001:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql:/var/lib/mysql
  wsgi_app:
    container_name: wsgi_app
    hostname: wsgi_app
    image: fogzan/alpenistsproject:latest
    build: 
      context: .
      dockerfile: Dockerfile.service
    ports:
      - 5000:5000
    restart: always
    depends_on:
      mysql_db:
        condition: service_healthy
    env_file:
      - .env
volumes:
  mysql:
