"""add desc

Revision ID: d8cde69c8b1c
Revises: 9d9d679be956
Create Date: 2023-12-14 11:18:35.251891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8cde69c8b1c'
down_revision = '9d9d679be956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climbings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climbings', schema=None) as batch_op:
        batch_op.drop_column('desc')

    # ### end Alembic commands ###
